sonar.organization=homorozeanu
sonar.projectKey=homorozeanu_param-diff
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
